import json
import urllib.request
from .core.config import settings

class MockLLM:
    def generate_hypotheses(self, question, evidence):
        return [
            {
                "statement": "A nonlinear regression model can reduce prediction error relative to a simple linear baseline on a suitable synthetic energy-system dataset.",
                "rationale": "The demonstration evidence describes nonlinear model behavior and motivates comparison against a simple baseline.",
                "supporting_evidence": [e.paper_id for e in evidence],
                "expected_outcome": "Lower mean absolute error than the baseline model.",
                "assumptions": ["The generated dataset contains nonlinear structure.", "Training and test distributions are comparable."],
                "testability": "Directly testable with a fixed-seed synthetic regression experiment.",
            }
        ]

class OpenAICompatibleLLM:
    def generate_hypotheses(self, question, evidence):
        prompt = {
            "model": settings.llm_model,
            "temperature": 0.2,
            "messages": [
                {"role": "system", "content": "Generate one cautious, testable scientific hypothesis. Return JSON only with statement, rationale, expected_outcome, assumptions, testability."},
                {"role": "user", "content": json.dumps({"question": question, "evidence": [e.model_dump() for e in evidence]})},
            ],
        }
        req = urllib.request.Request(
            settings.llm_base_url.rstrip("/") + "/chat/completions",
            data=json.dumps(prompt).encode(),
            headers={"Content-Type": "application/json", **({"Authorization": f"Bearer {settings.llm_api_key}"} if settings.llm_api_key else {})},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=30) as response:
            payload = json.loads(response.read())
        content = payload["choices"][0]["message"]["content"]
        try:
            return [json.loads(content)]
        except json.JSONDecodeError:
            return [{
                "statement": content,
                "rationale": "Generated by the configured local LLM.",
                "supporting_evidence": [e.paper_id for e in evidence],
                "expected_outcome": "Requires computational validation.",
                "assumptions": [],
                "testability": "Requires human review and experiment design.",
            }]

def get_llm():
    if settings.llm_provider.lower() == "local":
        return OpenAICompatibleLLM()
    return MockLLM()
